In [1]:
%run count_trihex63.py order6results --triple 63 32 1 --strict

Files: 31/31, triples: 481/481
Solutions in read files: 3,222; multiplied by 8: 25,776
Complement pairs: 256; match=256, mismatch=0, unknown=0
Missing files: 0; log errors: 0
Query (63, 32, 1): 26 solutions
Complement (63, 32, 1): 26 solutions
Saved CSV/JSON in: B:\Jupyter\Cprogram\trihexfinalprogram\order6analysis

In [3]:
import pandas as pd
import json
from pathlib import Path
from IPython.display import display, Markdown

folder = Path("trihex63_count_results")

# Configure pandas to display all rows and columns
pd.set_option("display.max_rows", None)
pd.set_option("display.max_columns", None)
pd.set_option("display.width", 200)

csv_files = {
    "Solution Counts by a47": "counts_by_a47.csv",
    "Solution Counts by Triple": "counts_by_triple.csv",
    "Complementary Triple Comparison": "complement_pairs.csv",
    "File-by-File Summary": "files_summary.csv",
}

dataframes = {}

# Load and display each CSV file
for title, filename in csv_files.items():
    df = pd.read_csv(folder / filename)
    dataframes[filename] = df

    display(Markdown(f"### {title} ({len(df):,} rows)"))
    display(df)

# Load and display the JSON summary
with open(folder / "summary.json", "r", encoding="utf-8") as f:
    summary = json.load(f)

display(Markdown("### Overall Solution Counts and Validation Summary (JSON)"))
display(
    pd.json_normalize(summary, sep=".")
    .T.rename(columns={0: "Value"})
)

### Solution Counts by a47 (31 rows)

    a47  a48_min  a48_max  combinations  count status
0    33       32       32             1      0   read
1    34       32       33             2     10   read
2    35       31       34             4     13   read
3    36       31       35             5     15   read
4    37       30       36             7     27   read
5    38       30       37             8     37   read
6    39       29       38            10     42   read
7    40       29       39            11     33   read
8    41       28       40            13     61   read
9    42       28       41            14     58   read
10   43       27       42            16    101   read
11   44       27       43            17    100   read
12   45       26       44            19    137   read
13   46       26       45            20    114   read
14   47       25       46            22    119   read
15   48       25       47            23    129   read
16   49       24       46            23    184   read
17   50       24       45            22    104   read
18   51       23       44            22    154   read
19   52       23       43            21    135   read
20   53       22       42            21    152   read
21   54       22       41            20    133   read
22   55       21       40            20    137   read
23   56       21       39            19    133   read
24   57       20       38            19    132   read
25   58       20       37            18    160   read
26   59       19       36            18    143   read
27   60       19       35            17    161   read
28   61       18       34            17    189   read
29   62       18       33            16    112   read
30   63       17       32            16    197   read

### Solution Counts by Triple (481 rows)

     a47  a48  a37  count status
0     33   32   31      0   read
1     34   32   30      6   read
2     34   33   29      4   read
3     35   31   30      4   read
4     35   32   29      0   read
5     35   33   28      2   read
6     35   34   27      7   read
7     36   31   29      2   read
8     36   32   28      0   read
9     36   33   27      4   read
10    36   34   26      6   read
11    36   35   25      3   read
12    37   30   29      7   read
13    37   31   28      4   read
14    37   32   27      0   read
15    37   33   26      8   read
16    37   34   25      2   read
17    37   35   24      2   read
18    37   36   23      4   read
19    38   30   28      6   read
20    38   31   27      8   read
21    38   32   26     10   read
22    38   33   25      1   read
23    38   34   24      3   read
24    38   35   23      6   read
25    38   36   22      2   read
26    38   37   21      1   read
27    39   29   28      3   read
28    39   30   27      2   read
29    39   31   26      1   read
30    39   32   25      4   read
31    39   33   24      4   read
32    39   34   23      4   read
33    39   35   22      3   read
34    39   36   21      6   read
35    39   37   20      4   read
36    39   38   19     11   read
37    40   29   27      2   read
38    40   30   26      3   read
39    40   31   25      4   read
40    40   32   24      0   read
41    40   33   23      2   read
42    40   34   22      7   read
43    40   35   21      5   read
44    40   36   20      4   read
45    40   37   19      1   read
46    40   38   18      2   read
47    40   39   17      3   read
48    41   28   27      4   read
49    41   29   26      6   read
50    41   30   25      4   read
51    41   31   24      2   read
52    41   32   23      2   read
53    41   33   22      1   read
54    41   34   21      7   read
55    41   35   20      6   read
56    41   36   19      6   read
57    41   37   18      4   read
58    41   38   17      1   read
59    41   39   16      8   read
60    41   40   15     10   read
61    42   28   26      2   read
62    42   29   25      3   read
63    42   30   24      7   read
64    42   31   23      1   read
65    42   32   22      4   read
66    42   33   21     11   read
67    42   34   20      6   read
68    42   35   19      4   read
69    42   36   18      3   read
70    42   37   17      5   read
71    42   38   16      5   read
72    42   39   15      4   read
73    42   40   14      1   read
74    42   41   13      2   read
75    43   27   26      1   read
76    43   28   25      6   read
77    43   29   24      5   read
78    43   30   23      7   read
79    43   31   22     11   read
80    43   32   21      8   read
81    43   33   20      4   read
82    43   34   19      9   read
83    43   35   18      3   read
84    43   36   17     10   read
85    43   37   16      7   read
86    43   38   15      5   read
87    43   39   14      4   read
88    43   40   13      6   read
89    43   41   12      5   read
90    43   42   11     10   read
91    44   27   25      4   read
92    44   28   24      4   read
93    44   29   23      6   read
94    44   30   22      6   read
95    44   31   21      4   read
96    44   32   20     14   read
97    44   33   19      7   read
98    44   34   18      5   read
99    44   35   17      2   read
100   44   36   16      2   read
101   44   37   15      6   read
102   44   38   14      1   read
103   44   39   13      8   read
104   44   40   12      9   read
105   44   41   11      7   read
106   44   42   10      5   read
107   44   43    9     10   read
108   45   26   25     11   read
109   45   27   24      1   read
110   45   28   23      6   read
111   45   29   22      4   read
112   45   30   21      9   read
113   45   31   20      7   read
114   45   32   19     20   read
115   45   33   18      8   read
116   45   34   17      4   read
117   45   35   16      7   read
118   45   36   15      6   read
119   45   37   14      2   read
120   45   38   13      4   read
121   45   39   12      8   read
122   45   40   11      8   read
123   45   41   10      9   read
124   45   42    9     11   read
125   45   43    8      8   read
126   45   44    7      4   read
127   46   26   24      2   read
128   46   27   23      4   read
129   46   28   22      3   read
130   46   29   21      3   read
131   46   30   20      5   read
132   46   31   19      8   read
133   46   32   18      2   read
134   46   33   17      5   read
135   46   34   16      2   read
136   46   35   15      5   read
137   46   36   14      4   read
138   46   37   13     12   read
139   46   38   12      6   read
140   46   39   11     11   read
141   46   40   10      4   read
142   46   41    9      6   read
143   46   42    8     17   read
144   46   43    7      9   read
145   46   44    6      3   read
146   46   45    5      3   read
147   47   25   24      3   read
148   47   26   23      1   read
149   47   27   22      5   read
150   47   28   21     10   read
151   47   29   20      2   read
152   47   30   19      4   read
153   47   31   18      5   read
154   47   32   17      0   read
155   47   33   16      7   read
156   47   34   15      9   read
157   47   35   14      2   read
158   47   36   13      5   read
159   47   37   12     10   read
160   47   38   11      3   read
161   47   39   10     12   read
162   47   40    9      0   read
163   47   41    8      8   read
164   47   42    7      4   read
165   47   43    6      3   read
166   47   44    5     11   read
167   47   45    4     13   read
168   47   46    3      2   read
169   48   25   23      8   read
170   48   26   22      5   read
171   48   27   21      7   read
172   48   28   20      2   read
173   48   29   19      7   read
174   48   30   18      2   read
175   48   31   17      7   read
176   48   32   16      6   read
177   48   33   15     13   read
178   48   34   14      3   read
179   48   35   13      7   read
180   48   36   12      5   read
181   48   37   11      6   read
182   48   38   10      5   read
183   48   39    9      0   read
184   48   40    8      1   read
185   48   41    7      3   read
186   48   42    6      7   read
187   48   43    5      6   read
188   48   44    4      4   read
189   48   45    3     10   read
190   48   46    2      6   read
191   48   47    1      9   read
192   49   24   23     10   read
193   49   25   22      4   read
194   49   26   21      5   read
195   49   27   20      6   read
196   49   28   19      6   read
197   49   29   18      5   read
198   49   30   17      9   read
199   49   31   16     13   read
200   49   32   15     12   read
201   49   33   14      3   read
202   49   34   13     10   read
203   49   35   12      3   read
204   49   36   11      5   read
205   49   37   10      8   read
206   49   38    9      9   read
207   49   39    8     13   read
208   49   40    7      6   read
209   49   41    6      3   read
210   49   42    5      6   read
211   49   43    4      9   read
212   49   44    3     14   read
213   49   45    2      9   read
214   49   46    1     16   read
215   50   24   22      1   read
216   50   25   21      4   read
217   50   26   20      1   read
218   50   27   19      2   read
219   50   28   18      4   read
220   50   29   17      2   read
221   50   30   16      3   read
222   50   31   15      3   read
223   50   32   14      2   read
224   50   33   13      4   read
225   50   34   12      3   read
226   50   35   11      5   read
227   50   36   10      9   read
228   50   37    9     14   read
229   50   38    8      2   read
230   50   39    7      5   read
231   50   40    6      4   read
232   50   41    5     10   read
233   50   42    4      7   read
234   50   43    3      5   read
235   50   44    2      2   read
236   50   45    1     12   read
237   51   23   22      2   read
238   51   24   21      6   read
239   51   25   20      8   read
240   51   26   19      4   read
241   51   27   18     12   read
242   51   28   17      5   read
243   51   29   16      7   read
244   51   30   15     10   read
245   51   31   14      4   read
246   51   32   13      6   read
247   51   33   12      2   read
248   51   34   11      8   read
249   51   35   10      6   read
250   51   36    9      4   read
251   51   37    8     10   read
252   51   38    7      6   read
253   51   39    6      4   read
254   51   40    5      5   read
255   51   41    4     16   read
256   51   42    3     11   read
257   51   43    2     10   read
258   51   44    1      8   read
259   52   23   21      5   read
260   52   24   20      9   read
261   52   25   19      8   read
262   52   26   18      6   read
263   52   27   17     10   read
264   52   28   16      5   read
265   52   29   15      3   read
266   52   30   14      3   read
267   52   31   13      2   read
268   52   32   12      8   read
269   52   33   11      7   read
270   52   34   10      6   read
271   52   35    9      4   read
272   52   36    8      9   read
273   52   37    7      3   read
274   52   38    6      2   read
275   52   39    5     10   read
276   52   40    4     11   read
277   52   41    3      8   read
278   52   42    2      6   read
279   52   43    1     10   read
280   53   22   21     10   read
281   53   23   20      7   read
282   53   24   19      8   read
283   53   25   18     11   read
284   53   26   17      3   read
285   53   27   16      6   read
286   53   28   15      5   read
287   53   29   14      5   read
288   53   30   13      8   read
289   53   31   12      7   read
290   53   32   11      2   read
291   53   33   10      3   read
292   53   34    9      6   read
293   53   35    8      9   read
294   53   36    7      5   read
295   53   37    6     12   read
296   53   38    5      3   read
297   53   39    4      8   read
298   53   40    3     17   read
299   53   41    2      6   read
300   53   42    1     11   read
301   54   22   20      5   read
302   54   23   19      9   read
303   54   24   18      4   read
304   54   25   17     12   read
305   54   26   16      5   read
306   54   27   15      8   read
307   54   28   14      9   read
308   54   29   13      6   read
309   54   30   12      6   read
310   54   31   11      3   read
311   54   32   10      6   read
312   54   33    9      5   read
313   54   34    8      5   read
314   54   35    7      6   read
315   54   36    6      2   read
316   54   37    5      4   read
317   54   38    4      8   read
318   54   39    3     12   read
319   54   40    2      9   read
320   54   41    1      9   read
321   55   21   20     10   read
322   55   22   19     11   read
323   55   23   18      6   read
324   55   24   17      0   read
325   55   25   16      0   read
326   55   26   15      9   read
327   55   27   14     14   read
328   55   28   13      4   read
329   55   29   12      4   read
330   55   30   11      6   read
331   55   31   10      5   read
332   55   32    9      8   read
333   55   33    8      4   read
334   55   34    7      5   read
335   55   35    6     10   read
336   55   36    5      8   read
337   55   37    4     10   read
338   55   38    3      5   read
339   55   39    2      8   read
340   55   40    1     10   read
341   56   21   19      8   read
342   56   22   18     17   read
343   56   23   17      8   read
344   56   24   16      1   read
345   56   25   15     13   read
346   56   26   14      2   read
347   56   27   13     10   read
348   56   28   12      9   read
349   56   29   11      9   read
350   56   30   10      5   read
351   56   31    9      4   read
352   56   32    8      8   read
353   56   33    7      3   read
354   56   34    6     11   read
355   56   35    5     13   read
356   56   36    4      2   read
357   56   37    3      3   read
358   56   38    2      5   read
359   56   39    1      2   read
360   57   20   19      4   read
361   57   21   18      9   read
362   57   22   17      4   read
363   57   23   16      3   read
364   57   24   15      6   read
365   57   25   14      5   read
366   57   26   13      6   read
367   57   27   12      3   read
368   57   28   11      5   read
369   57   29   10      6   read
370   57   30    9      5   read
371   57   31    8      3   read
372   57   32    7     10   read
373   57   33    6     13   read
374   57   34    5      3   read
375   57   35    4      9   read
376   57   36    3     14   read
377   57   37    2      5   read
378   57   38    1     19   read
379   58   20   18      3   read
380   58   21   17      3   read
381   58   22   16      7   read
382   58   23   15      3   read
383   58   24   14      4   read
384   58   25   13      4   read
385   58   26   12      2   read
386   58   27   11     12   read
387   58   28   10      2   read
388   58   29    9     10   read
389   58   30    8     11   read
390   58   31    7     13   read
391   58   32    6     26   read
392   58   33    5     11   read
393   58   34    4     12   read
394   58   35    3     13   read
395   58   36    2      7   read
396   58   37    1     17   read
397   59   19   18      3   read
398   59   20   17     11   read
399   59   21   16      6   read
400   59   22   15      6   read
401   59   23   14     10   read
402   59   24   13      5   read
403   59   25   12     10   read
404   59   26   11      3   read
405   59   27   10      4   read
406   59   28    9      8   read
407   59   29    8     13   read
408   59   30    7      3   read
409   59   31    6     11   read
410   59   32    5     16   read
411   59   33    4     11   read
412   59   34    3     10   read
413   59   35    2      5   read
414   59   36    1      8   read
415   60   19   17     13   read
416   60   20   16      4   read
417   60   21   15      9   read
418   60   22   14      7   read
419   60   23   13     16   read
420   60   24   12     11   read
421   60   25   11      8   read
422   60   26   10      8   read
423   60   27    9     10   read
424   60   28    8      2   read
425   60   29    7      9   read
426   60   30    6     12   read
427   60   31    5     11   read
428   60   32    4      4   read
429   60   33    3     18   read
430   60   34    2     10   read
431   60   35    1      9   read
432   61   18   17      2   read
433   61   19   16     10   read
434   61   20   15     14   read
435   61   21   14      5   read
436   61   22   13     11   read
437   61   23   12      8   read
438   61   24   11     17   read
439   61   25   10     12   read
440   61   26    9      5   read
441   61   27    8      3   read
442   61   28    7     14   read
443   61   29    6     13   read
444   61   30    5     10   read
445   61   31    4     18   read
446   61   32    3     12   read
447   61   33    2     11   read
448   61   34    1     24   read
449   62   18   16      6   read
450   62   19   15      9   read
451   62   20   14      2   read
452   62   21   13     10   read
453   62   22   12      6   read
454   62   23   11      6   read
455   62   24   10      9   read
456   62   25    9      8   read
457   62   26    8      5   read
458   62   27    7      5   read
459   62   28    6      7   read
460   62   29    5      5   read
461   62   30    4     10   read
462   62   31    3     11   read
463   62   32    2      6   read
464   62   33    1      7   read
465   63   17   16      9   read
466   63   18   15     16   read
467   63   19   14     12   read
468   63   20   13      8   read
469   63   21   12     10   read
470   63   22   11     11   read
471   63   23   10      9   read
472   63   24    9     10   read
473   63   25    8      2   read
474   63   26    7     19   read
475   63   27    6     17   read
476   63   28    5      8   read
477   63   29    4      9   read
478   63   30    3     24   read
479   63   31    2      7   read
480   63   32    1     26   read

### Complementary Triple Comparison (256 rows)

     a47  a48  a37  count  complement_a47  complement_a48  complement_a37  complement_count status
0     33   32   31      0              33              32              31                 0  MATCH
1     34   32   30      6              34              32              30                 6  MATCH
2     34   33   29      4              35              31              30                 4  MATCH
3     35   32   29      0              35              32              29                 0  MATCH
4     35   33   28      2              36              31              29                 2  MATCH
5     35   34   27      7              37              30              29                 7  MATCH
6     36   32   28      0              36              32              28                 0  MATCH
7     36   33   27      4              37              31              28                 4  MATCH
8     36   34   26      6              38              30              28                 6  MATCH
9     36   35   25      3              39              29              28                 3  MATCH
10    37   32   27      0              37              32              27                 0  MATCH
11    37   33   26      8              38              31              27                 8  MATCH
12    37   34   25      2              39              30              27                 2  MATCH
13    37   35   24      2              40              29              27                 2  MATCH
14    37   36   23      4              41              28              27                 4  MATCH
15    38   32   26     10              38              32              26                10  MATCH
16    38   33   25      1              39              31              26                 1  MATCH
17    38   34   24      3              40              30              26                 3  MATCH
18    38   35   23      6              41              29              26                 6  MATCH
19    38   36   22      2              42              28              26                 2  MATCH
20    38   37   21      1              43              27              26                 1  MATCH
21    39   32   25      4              39              32              25                 4  MATCH
22    39   33   24      4              40              31              25                 4  MATCH
23    39   34   23      4              41              30              25                 4  MATCH
24    39   35   22      3              42              29              25                 3  MATCH
25    39   36   21      6              43              28              25                 6  MATCH
26    39   37   20      4              44              27              25                 4  MATCH
27    39   38   19     11              45              26              25                11  MATCH
28    40   32   24      0              40              32              24                 0  MATCH
29    40   33   23      2              41              31              24                 2  MATCH
30    40   34   22      7              42              30              24                 7  MATCH
31    40   35   21      5              43              29              24                 5  MATCH
32    40   36   20      4              44              28              24                 4  MATCH
33    40   37   19      1              45              27              24                 1  MATCH
34    40   38   18      2              46              26              24                 2  MATCH
35    40   39   17      3              47              25              24                 3  MATCH
36    41   32   23      2              41              32              23                 2  MATCH
37    41   33   22      1              42              31              23                 1  MATCH
38    41   34   21      7              43              30              23                 7  MATCH
39    41   35   20      6              44              29              23                 6  MATCH
40    41   36   19      6              45              28              23                 6  MATCH
41    41   37   18      4              46              27              23                 4  MATCH
42    41   38   17      1              47              26              23                 1  MATCH
43    41   39   16      8              48              25              23                 8  MATCH
44    41   40   15     10              49              24              23                10  MATCH
45    42   32   22      4              42              32              22                 4  MATCH
46    42   33   21     11              43              31              22                11  MATCH
47    42   34   20      6              44              30              22                 6  MATCH
48    42   35   19      4              45              29              22                 4  MATCH
49    42   36   18      3              46              28              22                 3  MATCH
50    42   37   17      5              47              27              22                 5  MATCH
51    42   38   16      5              48              26              22                 5  MATCH
52    42   39   15      4              49              25              22                 4  MATCH
53    42   40   14      1              50              24              22                 1  MATCH
54    42   41   13      2              51              23              22                 2  MATCH
55    43   32   21      8              43              32              21                 8  MATCH
56    43   33   20      4              44              31              21                 4  MATCH
57    43   34   19      9              45              30              21                 9  MATCH
58    43   35   18      3              46              29              21                 3  MATCH
59    43   36   17     10              47              28              21                10  MATCH
60    43   37   16      7              48              27              21                 7  MATCH
61    43   38   15      5              49              26              21                 5  MATCH
62    43   39   14      4              50              25              21                 4  MATCH
63    43   40   13      6              51              24              21                 6  MATCH
64    43   41   12      5              52              23              21                 5  MATCH
65    43   42   11     10              53              22              21                10  MATCH
66    44   32   20     14              44              32              20                14  MATCH
67    44   33   19      7              45              31              20                 7  MATCH
68    44   34   18      5              46              30              20                 5  MATCH
69    44   35   17      2              47              29              20                 2  MATCH
70    44   36   16      2              48              28              20                 2  MATCH
71    44   37   15      6              49              27              20                 6  MATCH
72    44   38   14      1              50              26              20                 1  MATCH
73    44   39   13      8              51              25              20                 8  MATCH
74    44   40   12      9              52              24              20                 9  MATCH
75    44   41   11      7              53              23              20                 7  MATCH
76    44   42   10      5              54              22              20                 5  MATCH
77    44   43    9     10              55              21              20                10  MATCH
78    45   32   19     20              45              32              19                20  MATCH
79    45   33   18      8              46              31              19                 8  MATCH
80    45   34   17      4              47              30              19                 4  MATCH
81    45   35   16      7              48              29              19                 7  MATCH
82    45   36   15      6              49              28              19                 6  MATCH
83    45   37   14      2              50              27              19                 2  MATCH
84    45   38   13      4              51              26              19                 4  MATCH
85    45   39   12      8              52              25              19                 8  MATCH
86    45   40   11      8              53              24              19                 8  MATCH
87    45   41   10      9              54              23              19                 9  MATCH
88    45   42    9     11              55              22              19                11  MATCH
89    45   43    8      8              56              21              19                 8  MATCH
90    45   44    7      4              57              20              19                 4  MATCH
91    46   32   18      2              46              32              18                 2  MATCH
92    46   33   17      5              47              31              18                 5  MATCH
93    46   34   16      2              48              30              18                 2  MATCH
94    46   35   15      5              49              29              18                 5  MATCH
95    46   36   14      4              50              28              18                 4  MATCH
96    46   37   13     12              51              27              18                12  MATCH
97    46   38   12      6              52              26              18                 6  MATCH
98    46   39   11     11              53              25              18                11  MATCH
99    46   40   10      4              54              24              18                 4  MATCH
100   46   41    9      6              55              23              18                 6  MATCH
101   46   42    8     17              56              22              18                17  MATCH
102   46   43    7      9              57              21              18                 9  MATCH
103   46   44    6      3              58              20              18                 3  MATCH
104   46   45    5      3              59              19              18                 3  MATCH
105   47   32   17      0              47              32              17                 0  MATCH
106   47   33   16      7              48              31              17                 7  MATCH
107   47   34   15      9              49              30              17                 9  MATCH
108   47   35   14      2              50              29              17                 2  MATCH
109   47   36   13      5              51              28              17                 5  MATCH
110   47   37   12     10              52              27              17                10  MATCH
111   47   38   11      3              53              26              17                 3  MATCH
112   47   39   10     12              54              25              17                12  MATCH
113   47   40    9      0              55              24              17                 0  MATCH
114   47   41    8      8              56              23              17                 8  MATCH
115   47   42    7      4              57              22              17                 4  MATCH
116   47   43    6      3              58              21              17                 3  MATCH
117   47   44    5     11              59              20              17                11  MATCH
118   47   45    4     13              60              19              17                13  MATCH
119   47   46    3      2              61              18              17                 2  MATCH
120   48   32   16      6              48              32              16                 6  MATCH
121   48   33   15     13              49              31              16                13  MATCH
122   48   34   14      3              50              30              16                 3  MATCH
123   48   35   13      7              51              29              16                 7  MATCH
124   48   36   12      5              52              28              16                 5  MATCH
125   48   37   11      6              53              27              16                 6  MATCH
126   48   38   10      5              54              26              16                 5  MATCH
127   48   39    9      0              55              25              16                 0  MATCH
128   48   40    8      1              56              24              16                 1  MATCH
129   48   41    7      3              57              23              16                 3  MATCH
130   48   42    6      7              58              22              16                 7  MATCH
131   48   43    5      6              59              21              16                 6  MATCH
132   48   44    4      4              60              20              16                 4  MATCH
133   48   45    3     10              61              19              16                10  MATCH
134   48   46    2      6              62              18              16                 6  MATCH
135   48   47    1      9              63              17              16                 9  MATCH
136   49   32   15     12              49              32              15                12  MATCH
137   49   33   14      3              50              31              15                 3  MATCH
138   49   34   13     10              51              30              15                10  MATCH
139   49   35   12      3              52              29              15                 3  MATCH
140   49   36   11      5              53              28              15                 5  MATCH
141   49   37   10      8              54              27              15                 8  MATCH
142   49   38    9      9              55              26              15                 9  MATCH
143   49   39    8     13              56              25              15                13  MATCH
144   49   40    7      6              57              24              15                 6  MATCH
145   49   41    6      3              58              23              15                 3  MATCH
146   49   42    5      6              59              22              15                 6  MATCH
147   49   43    4      9              60              21              15                 9  MATCH
148   49   44    3     14              61              20              15                14  MATCH
149   49   45    2      9              62              19              15                 9  MATCH
150   49   46    1     16              63              18              15                16  MATCH
151   50   32   14      2              50              32              14                 2  MATCH
152   50   33   13      4              51              31              14                 4  MATCH
153   50   34   12      3              52              30              14                 3  MATCH
154   50   35   11      5              53              29              14                 5  MATCH
155   50   36   10      9              54              28              14                 9  MATCH
156   50   37    9     14              55              27              14                14  MATCH
157   50   38    8      2              56              26              14                 2  MATCH
158   50   39    7      5              57              25              14                 5  MATCH
159   50   40    6      4              58              24              14                 4  MATCH
160   50   41    5     10              59              23              14                10  MATCH
161   50   42    4      7              60              22              14                 7  MATCH
162   50   43    3      5              61              21              14                 5  MATCH
163   50   44    2      2              62              20              14                 2  MATCH
164   50   45    1     12              63              19              14                12  MATCH
165   51   32   13      6              51              32              13                 6  MATCH
166   51   33   12      2              52              31              13                 2  MATCH
167   51   34   11      8              53              30              13                 8  MATCH
168   51   35   10      6              54              29              13                 6  MATCH
169   51   36    9      4              55              28              13                 4  MATCH
170   51   37    8     10              56              27              13                10  MATCH
171   51   38    7      6              57              26              13                 6  MATCH
172   51   39    6      4              58              25              13                 4  MATCH
173   51   40    5      5              59              24              13                 5  MATCH
174   51   41    4     16              60              23              13                16  MATCH
175   51   42    3     11              61              22              13                11  MATCH
176   51   43    2     10              62              21              13                10  MATCH
177   51   44    1      8              63              20              13                 8  MATCH
178   52   32   12      8              52              32              12                 8  MATCH
179   52   33   11      7              53              31              12                 7  MATCH
180   52   34   10      6              54              30              12                 6  MATCH
181   52   35    9      4              55              29              12                 4  MATCH
182   52   36    8      9              56              28              12                 9  MATCH
183   52   37    7      3              57              27              12                 3  MATCH
184   52   38    6      2              58              26              12                 2  MATCH
185   52   39    5     10              59              25              12                10  MATCH
186   52   40    4     11              60              24              12                11  MATCH
187   52   41    3      8              61              23              12                 8  MATCH
188   52   42    2      6              62              22              12                 6  MATCH
189   52   43    1     10              63              21              12                10  MATCH
190   53   32   11      2              53              32              11                 2  MATCH
191   53   33   10      3              54              31              11                 3  MATCH
192   53   34    9      6              55              30              11                 6  MATCH
193   53   35    8      9              56              29              11                 9  MATCH
194   53   36    7      5              57              28              11                 5  MATCH
195   53   37    6     12              58              27              11                12  MATCH
196   53   38    5      3              59              26              11                 3  MATCH
197   53   39    4      8              60              25              11                 8  MATCH
198   53   40    3     17              61              24              11                17  MATCH
199   53   41    2      6              62              23              11                 6  MATCH
200   53   42    1     11              63              22              11                11  MATCH

### File-by-File Summary (31 rows)

    a47  a48_min  a48_max  combinations  headers  solutions  declared_total                           filename
0    33       32       32             1        1          0               0  trihex63_a47_33_all_a48_32_32.txt
1    34       32       33             2        2         10              10  trihex63_a47_34_all_a48_32_33.txt
2    35       31       34             4        4         13              13  trihex63_a47_35_all_a48_31_34.txt
3    36       31       35             5        5         15              15  trihex63_a47_36_all_a48_31_35.txt
4    37       30       36             7        7         27              27  trihex63_a47_37_all_a48_30_36.txt
5    38       30       37             8        8         37              37  trihex63_a47_38_all_a48_30_37.txt
6    39       29       38            10       10         42              42  trihex63_a47_39_all_a48_29_38.txt
7    40       29       39            11       11         33              33  trihex63_a47_40_all_a48_29_39.txt
8    41       28       40            13       13         61              61  trihex63_a47_41_all_a48_28_40.txt
9    42       28       41            14       14         58              58  trihex63_a47_42_all_a48_28_41.txt
10   43       27       42            16       16        101             101  trihex63_a47_43_all_a48_27_42.txt
11   44       27       43            17       17        100             100  trihex63_a47_44_all_a48_27_43.txt
12   45       26       44            19       19        137             137  trihex63_a47_45_all_a48_26_44.txt
13   46       26       45            20       20        114             114  trihex63_a47_46_all_a48_26_45.txt
14   47       25       46            22       22        119             119  trihex63_a47_47_all_a48_25_46.txt
15   48       25       47            23       23        129             129  trihex63_a47_48_all_a48_25_47.txt
16   49       24       46            23       23        184             184  trihex63_a47_49_all_a48_24_46.txt
17   50       24       45            22       22        104             104  trihex63_a47_50_all_a48_24_45.txt
18   51       23       44            22       22        154             154  trihex63_a47_51_all_a48_23_44.txt
19   52       23       43            21       21        135             135  trihex63_a47_52_all_a48_23_43.txt
20   53       22       42            21       21        152             152  trihex63_a47_53_all_a48_22_42.txt
21   54       22       41            20       20        133             133  trihex63_a47_54_all_a48_22_41.txt
22   55       21       40            20       20        137             137  trihex63_a47_55_all_a48_21_40.txt
23   56       21       39            19       19        133             133  trihex63_a47_56_all_a48_21_39.txt
24   57       20       38            19       19        132             132  trihex63_a47_57_all_a48_20_38.txt
25   58       20       37            18       18        160             160  trihex63_a47_58_all_a48_20_37.txt
26   59       19       36            18       18        143             143  trihex63_a47_59_all_a48_19_36.txt
27   60       19       35            17       17        161             161  trihex63_a47_60_all_a48_19_35.txt
28   61       18       34            17       17        189             189  trihex63_a47_61_all_a48_18_34.txt
29   62       18       33            16       16        112             112  trihex63_a47_62_all_a48_18_33.txt
30   63       17       32            16       16        197             197  trihex63_a47_63_all_a48_17_32.txt

### Overall Solution Counts and Validation Summary (JSON)

                    Value
expected_files         31
read_files             31
missing_files          []
expected_triples      481
covered_triples       481
observed_solutions   3222
multiplied_by_8     25776
complement_pairs      256
matched_pairs         256
mismatched_pairs       []
unknown_pairs           0
errors                 []
complete             True